name: Pull Request
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@v2.1.8

  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up GitHub package registry auth token
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      - uses: paralenz/actions/setup-node@v2.1.8
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Run linting
        run: yarn lint
      - name: Run tests
        run: yarn test --passWithNoTests